language: node_js
node_js:
  - "9"

services:
  - postgresql

 postgres:
 adapter: postgresql
 database: maindb
 username: postgres

before_install:
  - npm install -g npm@latest

before_script:
 - psql -c 'create database travis;' -U postgres
 - chmod 0777 ./node_modules/.bin/mocha
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

script:
  - npm test

after_success: npm run coverage
